### ISSUE TITLE
Testing should not be a package option

### ISSUE THREAD

**Issue by mpusz** [Croydon/conan-google_benchmark#1]
Hi,

I just found your repo. It turned out that I am working on the same subject for a long time now. You can find it here:
https://github.com/mpusz/conan-google-benchmark

I think you could reconsider having the following options:
"enable_testing=False","enable_gtest_tests=False"
They do not have a sense from user/client point of view. They might have a sense from the packaging point of view. I think that you could handle them similar to what I am doing in my repo.
https://github.com/mpusz/conan-google-benchmark

I will be talking about that today at CppCon.

Maybe you will find some other things there interesting too ;-)

Best

Mat

**Comment by Croydon** [comment]
Closing in favour of https://github.com/bincrafters/community/issues/449
